[package]
name = "abi"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
tonic = { version = "0.13.1", features = ["gzip"] }

[build-dependencies]
tonic-build = "0.13.1"
